# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm6450-modules/motorola/modules/include
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm6450-modules/motorola/modules/drivers/power/sc8541_mmi_iio

obj-m += sc8541_mmi_iio.o
